/** Search queries for full cafe coverage in Barcelona. */
export const SEARCH_QUERIES = [
  "best coffee Barcelona",
  "specialty coffee Barcelona",
  "coffee shop Barcelona",
  "cafe Barcelona",
  "café Barcelona",
  "coffee near me",
  "coffee shop near me",
  "best specialty coffee Barcelona",
  "brunch Barcelona",
  "cafe to work Barcelona",
  "café to work Barcelona",
  "coffee roasters Barcelona",
  "espresso bar Barcelona",
  "flat white Barcelona",
  "filter coffee Barcelona",
  "third wave coffee Barcelona",
  "artisan coffee Barcelona",
  "coffee takeaway Barcelona",
  "breakfast cafe Barcelona",
  "brunch cafe Barcelona",
  "laptop friendly cafe Barcelona",
  "coworking cafe Barcelona",
  "wifi cafe Barcelona",
  "pet friendly cafe Barcelona",
  "vegan cafe Barcelona",
  "coffee terrace Barcelona",
  "coffee El Born",
  "coffee Eixample",
  "coffee Poblenou",
  "coffee Gràcia",
  "coffee Gothic Quarter",
  "specialty coffee El Born",
  "specialty coffee Eixample",
  "specialty coffee Poblenou",
  "specialty coffee Gràcia",
  "specialty coffee Gothic Quarter",
];
